<?
    $this->headTitle('Citizen Services - Birth Certificate Test');
    $this->headLink()->appendStylesheet('/css/bootstrap.min.css'); 
    $this->headLink()->appendStylesheet('/css/default/wittywonders.css'); 
    $this->headScript()->appendScript('/js/bootstrap.min.js'); 
    $this->headMeta()->appendName('keywords', 'philippines, dfa, poea, nso, passport, birth certificate, marriage certificate, death certificate, overseas exit clearance, wednesday witty wonders')
                     ->appendName('description', 'Witty Wonders is a collection of wonderful facts from around the world. Once in a while, we stumble upon these trivia and we have compiled them for your appreciation and additional knowledge. Every Wednesday, we will post a new fact along with the answer and other information for you to view, review, and share with your friends.');
?>

<div id="birth-cert-test">
	<div class="col-lg-12">
		<h3 class="text-center">The Citizen Services Birth Certificate Appraisal Test</h3>
		<br><br>
		<p>
			CITIZEN SERVICE'S Birth Certificate Appraisal Test (BCAT) is a derived method of determining how well your existing NSO birth certificate ranks among the various needs, uses, and requirements for this very important life document.
		</p>
		<p>
			Is your NSO birth record good enough for passport application? Can you apply for a VISA without any hassle? Are your records consistent across all sectors?
		</p>
		<p>
			Taking the BCAT will determine a rating (10-100) for your birth certificate in relation to these concerns and various other factors we encountered over the last 15 years. Taking into account questions, problems, and other pertinent information, the test will also give you pointers on how to address your birth certificate concerns.
		</p>
		<p>
			So take the test and find out how well your birth certificate ranks.
		</p>
		<br><br>
		<div class="text-center">
			<a href="birth-certificate-test/start" class="btn btn-success btn-lg">Click here to START</a>
		</div>
	</div>
</div>
